project_id = "appescala"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "https://atos-agenda.netlify.app"
additional_redirect_urls = [
  "https://atos-agenda.netlify.app/auth/callback",
  "http://localhost:3000/auth/callback",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = false
max_frequency = "1s"
otp_length = 6

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
